version: '3'

services:
  database:
    image: postgres:14.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: '--data-checksums --encoding=UTF8'
