name: Build apps 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version-file: 'front/.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'front/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install 
      - name: Build app 
        run: pnpm run build

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version-file: 'back/.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'back/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install 
      - name: Build app 
        run: pnpm run build
      - name: Run tests
        run: pnpm run test
